### ISSUE TITLE
Migrate gRPC API

### ISSUE THREAD

**Issue by prdlk** [sonr-io/sonr#192]
### Premise

Since we are planning to remove our dependency for buf.build on sonr-io/core, we need to modify our definitions for our Highway proto files. Currently,
we are utilizing the buf.build import system in order to reference the published types from sonr-io/blockchain and then convert them into the types from
the actual module. As you can see this redundency is an unnecessary bottleneck.

### To-Do

* [ ] Plan updated Highway Method types for the Protobuf gRPC service
* [ ] Require only necessary parameters in order to construct messages to send to the blockchain
* [ ] Implement updated types in the /highway directory

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202534192193079) by [Unito](https://www.unito.io)
