### ISSUE TITLE
Define bucket categories for app-specific, mailbox, and vault

### ISSUE THREAD

**Issue by prdlk** [sonr-io/sonr#471]
## To-Do

* [x] Update [ADR-3](https://docs.sonr.io/posts/architecture/adr-003) to contain categories of buckets
* [x] Update `proto/bucket` to match [ADR-3](https://docs.sonr.io/posts/architecture/adr-003) CRUD methods
* [x] Push updated types to [Buf.build](buf.build/sonr-io/sonr)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202588794949851) by [Unito](https://www.unito.io)
