### ISSUE TITLE
SQL User Mailboxes

### ISSUE THREAD

**Issue by prdlk** [sonr-io/sonr#781]
### Summary

> Use IcefireDB to provide Services a way to communicate end-to-end encrypted with a private self-custody mailbox.

### Tasks

* [ ] Add icefiresql image to docker-compose
* [ ] Configure encryption between DID controller and SQL table values
* [ ] Provide REST API routes for MySQL protocol
* [ ] Integrate ServiceRecord's as resolution endpoint
